blog/urls.py
from django.urls import path
from . import views

app_name = "blog"
urlpatterns = [
    path('post/<post_slug>/edit/', views.post_edit, name='post_edit'),
    path('post/new-post/', views.post_new, name='post_new'),
    path('post/<post_slug>/', views.post_detail, name='post_detail'),
    path('user/<str:username>/', views.user_detail, name='user_detail'),
    path('tag/<tag_slug>',views.tag_details,name='Tag_post'),
    path('cat/<category_slug>',views.cat_details,name='Cat_post'),
    path('post/cat', views.cat_list, name='Cat_list'),
    path('post/tag', views.tag_list, name='Tag_list'),
    path('comment/reply/', views.reply_page, name="reply"),
    path('edit_profile/', views.edit_profile, name='edit_profile'),
    path('register/', views.register_view, name='register'),
    path('login/', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout'),
    path('bulk_post_upload/',views.bulk_post_upload, name='bulk_post_upload'),
    path('', views.post_list, name='post_list'),
]

polls/urls.py
from django.urls import path
from django.contrib.auth.decorators import login_required


from . import views

app_name = "polls"
urlpatterns = [
    path("<que_slug>/results/", views.ResultsView.as_view(), name="results"),
    path("<que_slug>/vote/", views.vote, name="vote"),
    path("<que_slug>/", views.DetailView.as_view(), name="detail"),
    path("", views.IndexView.as_view(login_url='/login'), name="index"),
]

project01/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
urlpatterns = [
    path('admin/', admin.site.urls),
    path("polls/", include("polls.urls")),
    path('api/',include('blog.apiUrls')),
    path('accounts/', include('allauth.urls')),
    path('accounts/', include('allauth.socialaccount.urls')),
    path('', include('blog.urls')),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
import os
from django.core.files import File
from django.utils import timezone
from django.urls import reverse

from django.utils.html import mark_safe
from django.conf import settings
from django.contrib.auth.models import AbstractUser
from django.db import models
from django.dispatch import receiver
from django.db.models.signals import post_save, m2m_changed

from autoslug import AutoSlugField
from ckeditor.fields import RichTextField

from blog.utils import generate_audio, send_push_notification

COUNTRY_CHOICES = [
    ('CN', 'China'),
    ('IN', 'India'),
    ('US', 'United States'),
    ('ID', 'Indonesia'),
    ('PK', 'Pakistan'),
    ('BR', 'Brazil'),
    ('NG', 'Nigeria'),
    ('BD', 'Bangladesh'),
    ('RU', 'Russia'),
    ('MX', 'Mexico'),
    ('JP', 'Japan'),
    ('ET', 'Ethiopia'),
    ('PH', 'Philippines'),
    ('EG', 'Egypt'),
    ('VN', 'Vietnam'),
    ('CD', 'Democratic Republic of the Congo'),
    ('TR', 'Turkey'),
    ('IR', 'Iran'),
    ('DE', 'Germany'),
    ('TH', 'Thailand'),
    ('GB', 'United Kingdom'),
    ('FR', 'France'),
    ('IT', 'Italy'),
    ('TZ', 'Tanzania'),
    ('ZA', 'South Africa'),
    ('KR', 'South Korea'),
    ('CO', 'Colombia'),
    ('KE', 'Kenya'),
    ('AR', 'Argentina'),
    ('UA', 'Ukraine'),
    ('SD', 'Sudan'),
    ('PL', 'Poland'),
    ('DZ', 'Algeria'),
    ('CA', 'Canada'),
    ('UG', 'Uganda'),
    ('MA', 'Morocco'),
    ('PE', 'Peru'),
    ('IQ', 'Iraq'),
    ('SA', 'Saudi Arabia'),
    ('UZ', 'Uzbekistan'),
    ('MY', 'Malaysia'),
    ('VE', 'Venezuela'),
    ('AF', 'Afghanistan'),
    ('GH', 'Ghana'),
    ('NP', 'Nepal'),
    ('YE', 'Yemen'),
    ('KP', 'North Korea'),
    ('MG', 'Madagascar'),
    ('CM', 'Cameroon'),
    ('CI', 'Ivory Coast'),
    ('AU', 'Australia'),
    ('NE', 'Niger'),
    ('TW', 'Taiwan'),
    ('LK', 'Sri Lanka'),
    ('BF', 'Burkina Faso'),
    ('ML', 'Mali'),
    ('RO', 'Romania'),
    ('MW', 'Malawi'),
    ('CL', 'Chile'),
    ('KZ', 'Kazakhstan'),
    ('ZM', 'Zambia'),
    ('GT', 'Guatemala'),
    ('EC', 'Ecuador'),
    ('SY', 'Syria'),
    ('NL', 'Netherlands'),
    ('SN', 'Senegal'),
    ('KP', 'Cambodia'),
    ('TD', 'Chad'),
    ('SO', 'Somalia'),
    ('ZW', 'Zimbabwe'),
    ('RW', 'Rwanda'),
    ('GN', 'Guinea'),
    ('BJ', 'Benin'),
    ('TN', 'Tunisia'),
    ('BE', 'Belgium'),
    ('CU', 'Cuba'),
    ('BO', 'Bolivia'),
    ('HT', 'Haiti'),
    ('GR', 'Greece'),
    ('DO', 'Dominican Republic'),
    ('CZ', 'Czech Republic'),
    ('PT', 'Portugal'),
    ('SV', 'El Salvador'),
    ('HN', 'Honduras'),
    ]
LANGUAGE_CODE_MAPPING = {
    'en': 'English',
    'es': 'Spanish',
    'fr': 'French',
    'de': 'German',
    'it': 'Italian',
    'pt': 'Portuguese',
    'ru': 'Russian',
    'ja': 'Japanese',
    'zh-CN': 'Chinese (Simplified)',
    'ar': 'Arabic',
    'hi': 'Hindi',
    'ko': 'Korean',
    'tr': 'Turkish',
    'nl': 'Dutch',
    'sv': 'Swedish',
    'fi': 'Finnish',
    'no': 'Norwegian',
    'da': 'Danish',
    'pl': 'Polish',
    'vi': 'Vietnamese',
    'th': 'Thai',
    'id': 'Indonesian',
    'ms': 'Malay',
    'he': 'Hebrew',
    'el': 'Greek',
    'cs': 'Czech',
    'hu': 'Hungarian',
    'ro': 'Romanian',
    'bg': 'Bulgarian',
    'uk': 'Ukrainian',
    'sk': 'Slovak',
    'sl': 'Slovenian',
    'hr': 'Croatian',
    'sr': 'Serbian',
    'mk': 'Macedonian',
    'sq': 'Albanian',
    'et': 'Estonian',
    'lv': 'Latvian',
    'lt': 'Lithuanian',
    'hy': 'Armenian',
    'ka': 'Georgian',
    'uz': 'Uzbek',
    'kk': 'Kazakh',
    'ky': 'Kyrgyz',
    'tg': 'Tajik',
    'tk': 'Turkmen',
    'mn': 'Mongolian',
    'ps': 'Pashto',
    'fa': 'Persian',
    'ur': 'Urdu',
    'bn': 'Bengali',
    'pa': 'Punjabi',
    'gu': 'Gujarati',
    'or': 'Odia',
    'mr': 'Marathi',
    'ne': 'Nepali',
    'si': 'Sinhala',
    'ml': 'Malayalam',
    'kn': 'Kannada',
    'ta': 'Tamil',
    'te': 'Telugu',
    'am': 'Amharic',
    'sw': 'Swahili',
    'yo': 'Yoruba',
    'ha': 'Hausa',
    'ig': 'Igbo',
    'zu': 'Zulu',
    'xh': 'Xhosa',
    'af': 'Afrikaans',
    'is': 'Icelandic',
    'ga': 'Irish',
    'mt': 'Maltese',
    'th': 'Thai',
    'km': 'Khmer',
    'lo': 'Lao',
    'my': 'Burmese',
    'dz': 'Dzongkha',
    'yi': 'Yiddish',
    'jw': 'Javanese',
    'su': 'Sundanese',
    'ms': 'Malay',
    'fil': 'Filipino',
    'ceb': 'Cebuano',
    'hmn': 'Hmong',
    'haw': 'Hawaiian',
    'sm': 'Samoan',
    'to': 'Tongan',
    'mi': 'Maori',
    'fj': 'Fijian',
}

GENDER_CHOICES = (
        ('M', 'Male'),
        ('F', 'Female'),
    )
LANG_CHOICES = (
    ('en', 'English'),
    ('es', 'Spanish'),
    ('fr', 'French'),
    ('de', 'German'),
    ('it', 'Italian'),
    ('pt', 'Portuguese'),
    ('ru', 'Russian'),
    ('ja', 'Japanese'),
    ('zh-CN', 'Chinese (Simplified)'),
    ('ar', 'Arabic'),
    ('hi', 'Hindi'),
    ('ko', 'Korean'),
    ('tr', 'Turkish'),
    ('nl', 'Dutch'),
    ('sv', 'Swedish'),
    ('fi', 'Finnish'),
    ('no', 'Norwegian'),
    ('da', 'Danish'),
    ('pl', 'Polish'),
    ('vi', 'Vietnamese'),
    ('th', 'Thai'),
    ('id', 'Indonesian'),
    ('ms', 'Malay'),
    ('he', 'Hebrew'),
    ('el', 'Greek'),
    ('cs', 'Czech'),
    ('hu', 'Hungarian'),
    ('ro', 'Romanian'),
    ('bg', 'Bulgarian'),
    ('uk', 'Ukrainian'),
    ('sk', 'Slovak'),
    ('sl', 'Slovenian'),
    ('hr', 'Croatian'),
    ('sr', 'Serbian'),
    ('mk', 'Macedonian'),
    ('sq', 'Albanian'),
    ('et', 'Estonian'),
    ('lv', 'Latvian'),
    ('lt', 'Lithuanian'),
    ('hy', 'Armenian'),
    ('ka', 'Georgian'),
    ('uz', 'Uzbek'),
    ('kk', 'Kazakh'),
    ('ky', 'Kyrgyz'),
    ('tg', 'Tajik'),
    ('tk', 'Turkmen'),
    ('mn', 'Mongolian'),
    ('ps', 'Pashto'),
    ('fa', 'Persian'),
    ('ur', 'Urdu'),
    ('bn', 'Bengali'),
    ('pa', 'Punjabi'),
    ('gu', 'Gujarati'),
    ('or', 'Odia'),
    ('mr', 'Marathi'),
    ('ne', 'Nepali'),
    ('si', 'Sinhala'),
    ('ml', 'Malayalam'),
    ('kn', 'Kannada'),
    ('ta', 'Tamil'),
    ('te', 'Telugu'),
    ('ur', 'Urdu'),
    ('am', 'Amharic'),
    ('sw', 'Swahili'),
    ('yo', 'Yoruba'),
    ('ha', 'Hausa'),
    ('ig', 'Igbo'),
    ('zu', 'Zulu'),
    ('xh', 'Xhosa'),
    ('af', 'Afrikaans'),
    ('is', 'Icelandic'),
    ('ga', 'Irish'),
    ('mt', 'Maltese'),
    ('th', 'Thai'),
    ('km', 'Khmer'),
    ('lo', 'Lao'),
    ('my', 'Burmese'),
    ('si', 'Sinhala'),
    ('ka', 'Georgian'),
    ('mn', 'Mongolian'),
    ('dz', 'Dzongkha'),
    ('yi', 'Yiddish'),
    ('jw', 'Javanese'),
    ('su', 'Sundanese'),
    ('ms', 'Malay'),
    ('fil', 'Filipino'),
    ('ceb', 'Cebuano'),
    ('hmn', 'Hmong'),
    ('haw', 'Hawaiian'),
    ('sm', 'Samoan'),
    ('to', 'Tongan'),
    ('mi', 'Maori'),
    ('fj', 'Fijian'),
)

COUNTRY_CHOICES = sorted(COUNTRY_CHOICES, key=lambda x: x[1])
class Language(models.Model):
    name = models.CharField(max_length=100, choices=LANG_CHOICES)
    code = models.CharField(max_length=10, null=True, blank=True)

    def __str__(self):
        return LANGUAGE_CODE_MAPPING.get(self.code,'')

    def save(self, *args, **kwargs):
        self.code = self.name  # Assign the name to the code field
        send_push_notification(title="Language", body="Language Created", data={"key": "value"})
        super().save(*args, **kwargs)
        
       

class CustomUser(AbstractUser):
    gender = models.CharField(max_length=60,choices=GENDER_CHOICES,blank=True)
    city = models.CharField(max_length=80,blank=True)
    state = models.CharField(max_length=90,blank=True)
    country = models.CharField(max_length=50,blank=True,default='IN',choices=COUNTRY_CHOICES)
    designation = models.CharField(max_length=50,null=True,blank=True)
    img = models.ImageField(blank=True,null=True,upload_to='profile_images/',default='default_img.jpg')
    phone = models.PositiveBigIntegerField(blank=True,default=0000000)
    pincode = models.PositiveIntegerField(blank=True,null=True)
    address = models.TextField(max_length=50,blank=True,null=True)
    preferred_language = models.ForeignKey(Language, on_delete=models.SET_NULL, null=True, blank=True)
    dob = models.DateField(blank=True,null=True)
    
    def __str__(self):
        return self.username
    
    def img_preview(self): 
        return mark_safe('<img src = "{url}" width = "25"/>'.format(
             url = self.img.url 
         ))
        
    def img_preview2(self): 
        return mark_safe('<img src = "{url}" width = "100"/>'.format(
             url = self.img.url
         ))
    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)
        # send_push_notification(title="user created", body="user Created", data={"key": "value"})


class Category(models.Model):
    title = models.CharField(max_length=60)
    description = models.TextField(max_length=120,default="Hii this is the discription")
    def __str__(self):
        return self.title
    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)
        send_push_notification(title="Category", body="Category Created", data={"key": "value"})


class Tag(models.Model):
    name = models.CharField(max_length=50, unique=True,null=True)
    description = models.TextField(max_length=120,default="Hii this is the discription")
    def __str__(self):
        return self.name
    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)
        send_push_notification(title="Tag", body="Tag Created", data={"key": "value"})
   
    
class Post(models.Model):
    author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE,null=True)
    post_cat = models.ForeignKey(Category,on_delete=models.CASCADE,null=True)
    tags = models.ManyToManyField(Tag)
    post_slug = AutoSlugField(populate_from='title', unique=True, null=True, default=None,always_update=True )  
    title = models.CharField(max_length=200)
    text = RichTextField()
    created_date = models.DateTimeField(default=timezone.now, editable=False)
    published_date = models.DateTimeField(blank=True, null=True,default=timezone.now)

blog/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, UserChangeForm

from ckeditor.widgets import CKEditorWidget

from .models import *



class BulkPostUploadForm(forms.Form):
    excel_file = forms.FileField()

class ReadOnlyAudioPlayerWidget(forms.Widget):
    def render(self, name, value, attrs=None, renderer=None):
        if value:
            return mark_safe('<audio controls src="{}"></audio>'.format(value.url))
        return "No audio file"
    
class PostForm(forms.ModelForm):
    text = forms.CharField(widget=CKEditorWidget())
    audio_file = forms.FileField(widget=ReadOnlyAudioPlayerWidget(), required=False)
    class Meta:
        model = Post
        fields = ('title', 'text','post_cat','tags','image','feature_img')

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment   
        fields = ('name', 'body')      
        
class CustomUserCreationForm(UserCreationForm):
    class Meta:
        model = CustomUser
        fields = ('username', 'email', 'password1', 'password2', 'preferred_language')
        
        
class CustomUserChangeForm(UserChangeForm):
    class Meta(UserCreationForm.Meta):
        model = CustomUser
        fields =("email", "phone", "first_name", "last_name", "gender", "dob", "designation", "address", "pincode", "city", "state", "country", "img","preferred_language")
        widgets = {
            'dob': forms.DateInput(attrs={'type': 'date'}),
        }

blog/templates/blog/Cat_list.html
{% extends 'blog/base.html' %}

{% block content %}

<h1>Categories</h1>

<div class="catContainer">
    {% for categorie in categories %}
    <a class="text-decoration-none text-black " href="{% url 'blog:Cat_post' category_slug=categorie.title %}">
        <p>
            {{categorie.title}}
        </p>
    </a>
    {% endfor %}
</div>

{% endblock %}

blog/templates/blog/base.html
{% load static %}
{% load google_translate %}
<!DOCTYPE html>
<html>

<head>
    <title>Django Girls blog</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css"
        integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Lobster&subset=latin,latin-ext">
    <link rel="stylesheet" href="{% static 'css/blog.css' %}">
    <script src="https://www.gstatic.com/firebasejs/8.6.3/firebase-app.js"></script>
    <script src="https://www.gstatic.com/firebasejs/8.6.3/firebase-analytics.js"></script>
    <script src="https://www.gstatic.com/firebasejs/8.6.3/firebase-messaging.js"></script>
</head>
<style>
    .skiptranslate iframe{
        visibility: hidden !important;
    }

</style>

<body class="top-0">
    <header class="page-header bg-dark text-light  ">
        <div class="container d-flex justify-content-between align-items-center">
            <div class="btn-group d-flex flex-column">
                <a id="link1" class="btn btn-primary mx-3  mb-2" href="{% url 'polls:index' %}">Poll App</a>
                <a id="link2" class="btn btn-primary  mb-2" href="{% url 'blog:post_list' %}">Blog App</a>
                {% if user.is_authenticated %}
                <a class="btn btn-primary" href="{% url 'blog:logout' %}">Logout</a>
                {% else %}
                <a class="btn btn-primary" href="{% url 'blog:login' %}?next={{request.path}}">Login</a>
                {% endif %}
            </div>
            {% if user.is_authenticated %}
            <a href="{% url 'blog:post_new' %}" class="btn btn-success mx-4">
                +
            </a>
            {% endif %}

            <div class="d-flex  flex-row  align-items-center">
                
                <h1 class="h3 mb-0" id="blogHome" ><a class="text-light text-decoration-none" href="{% url 'blog:post_list' %}">Home</a></h1></div>
                <h1 class="h3 mb-0"><a class="text-light text-decoration-none"
                        href="{% url 'blog:Cat_list' %}">Category</a></h1>
                <h1 class="h3 mb-0"><a class="text-light text-decoration-none" href="{% url 'blog:Tag_list' %}">Tags</a>
                </h1>
                {% if user.is_authenticated %}
                <h1 class="h3 mb-0"><a class="text-light text-decoration-none"
                        href="{% url 'blog:user_detail' username=user.username %}">Profile</a></h1>

                {% else %}
                <a class="btn btn-primary" href="{% url 'blog:register' %}">Register</a>
                {% endif %}
                <a class="btn btn-primary" href="{% url 'blog:bulk_post_upload' %}">Bulk upload</a>
            </div>

            

        </div>
    </header>
    <main class="content container">
        <div class="row">
            <div class="col">
                {% block content %}
                {% endblock %}
            </div>
        </div>
    </main>
    <footer class="mb-5 p-5">
        {% google_translate type='horizontal' %}
       

    </footer>
</body>


<script>
function googleTranslateElementInit() {
        new google.translate.TranslateElement({  layout: google.translate.TranslateElement.InlineLayout.SIMPLE }, 'google_translate_element');
    }
  

    var currentUrl = window.location.pathname;
    if (currentUrl == "/polls/") {
        document.querySelector("#link1").style.display = 'none'
        document.querySelector("#link2").style.display = 'block'
        document.querySelector("#blogHome").style.display = 'none'

    }
    else {
        document.querySelector("#link1").style.display = 'block'
        document.querySelector("#link2").style.display = 'none'
        document.querySelector("#blogHome").style.display = 'block'
    }
    const LANGUAGE_CODE_MAPPING_REVERSED = {
    'English': 'en',
    'Spanish': 'es',
    'French': 'fr',
    'German': 'de',
    'Italian': 'it',
    'Portuguese': 'pt',
    'Russian': 'ru',
    'Japanese': 'ja',
    'Chinese (Simplified)': 'zh-CN',
    'Arabic': 'ar',
    'Hindi': 'hi',
    'Korean': 'ko',
    'Turkish': 'tr',
    'Dutch': 'nl',
    'Swedish': 'sv',
    'Finnish': 'fi',
    'Norwegian': 'no',
    'Danish': 'da',
    'Polish': 'pl',
    'Vietnamese': 'vi',
    'Thai': 'th',
    'Indonesian': 'id',
    'Malay': 'ms',
    'Hebrew': 'he',
    'Greek': 'el',
    'Czech': 'cs',
    'Hungarian': 'hu',
    'Romanian': 'ro',
    'Bulgarian': 'bg',
    'Ukrainian': 'uk',
    'Slovak': 'sk',
    'Slovenian': 'sl',
    'Croatian': 'hr',
    'Serbian': 'sr',
    'Macedonian': 'mk',
    'Albanian': 'sq',
    'Estonian': 'et',
    'Latvian': 'lv',
    'Lithuanian': 'lt',
    'Armenian': 'hy',
    'Georgian': 'ka',
    'Uzbek': 'uz',
    'Kazakh': 'kk',
    'Kyrgyz': 'ky',
    'Tajik': 'tg',
    'Turkmen': 'tk',
    'Mongolian': 'mn',
    'Pashto': 'ps',
    'Persian': 'fa',
    'Urdu': 'ur',
    'Bengali': 'bn',
    'Punjabi': 'pa',
    'Gujarati': 'gu',
    'Odia': 'or',
    'Marathi': 'mr',
    'Nepali': 'ne',
    'Sinhala': 'si',
    'Malayalam': 'ml',
    'Kannada': 'kn',
    'Tamil': 'ta',
    'Telugu': 'te',
    'Amharic': 'am',
    'Swahili': 'sw',
    'Yoruba': 'yo',
    'Hausa': 'ha',
    'Igbo': 'ig',
    'Zulu': 'zu',
    'Xhosa': 'xh',
    'Afrikaans': 'af',
    'Icelandic': 'is',
    'Irish': 'ga',
    'Maltese': 'mt',
    'Khmer': 'km',
    'Lao': 'lo',
    'Burmese': 'my',
    'Dzongkha': 'dz',
    'Yiddish': 'yi',
    'Javanese': 'jw',
    'Sundanese': 'su',
    'Filipino': 'fil',
    'Cebuano': 'ceb',
    'Hmong': 'hmn',
    'Hawaiian': 'haw',
    'Samoan': 'sm',
    'Tongan': 'to',
    'Maori': 'mi',
    'Fijian': 'fj',
}

    document.addEventListener("DOMContentLoaded", function() {
            var userLanguage = "{{user.preferred_language}}";
            if (LANGUAGE_CODE_MAPPING_REVERSED[userLanguage]) {
               
                let ele = document.getElementById("google_translate_element")
                if(ele){
                    setTimeout(() => {
                        let ch=ele.classList.toggle('d-none')
                        console.log(ch)

                    }, 500);
                }

                var currentUrl = window.location.href;
                var cleanUrl = currentUrl.replace(/#googtrans\([^)]*\)/, '');
                var newUrl = cleanUrl + `#googtrans(${LANGUAGE_CODE_MAPPING_REVERSED[userLanguage]})`;
                window.location.href = newUrl;
            }
            // else{
            //     var currentUrl = window.location.href;
            //     var cleanUrl = currentUrl.replace(/#googtrans\([^)]*\)/, '');
            //     var newUrl = cleanUrl + `#googtrans(en)`;
            //     window.location.href = newUrl;
            // }
            

        });
        
</script>


</html>

blog/templates/blog/post_detail.html
{% extends 'blog/base.html' %}
{% load static %}


{% block content %}
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css"
    integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">

<article class="post w-100">
    <aside class="actions">
        <a class="btn btn-secondary" href="{% url 'blog:post_edit' post_slug=post.post_slug %}">
            Edit
        </a>
    </aside>
    <div class="d-flex align-items-center justify-content-around m-auto">
        {% if post.feature_img%}
        <!-- {{post.feature_img.url}} -->
        {% if "%" in post.image.url %}
            <img src="{{post.feature_img}}" class="w-50 aspect-ratio-1x1" alt="{{ post.title }}" >
        {% else %}
            <img src="{{ post.feature_img.url }}" class="w-50 aspect-ratio-1x1" alt="{{ post.title }}" >
        {% endif %}
                       
        <!-- <img src="{{post.feature_img.url}}" alt="" srcset="" class="w-50 aspect-ratio-1x1"> -->
        {% endif%}
    </div>
    {% if post.post_cat %}
    <a class="text-decoration-none text-black" href="{% url 'blog:Cat_post' category_slug=post.post_cat.title %}">
        <p class="card-text text-decoration-none">Category: {{ post.post_cat.title }}</p>
    </a>
{% endif %}


    {% if post.published_date %}
    <time class="date">
        {{ post.published_date|timesince }}
    </time>
    {% endif %}
    <h2 class="card-title mb-3 custom-font text-decoration-none">{{ post.title }}</h2>
    <div class="tags mb-2 mt-2">
        {% for tag in post.tags.all %}
        <a href="{% url 'blog:Tag_post' tag_slug=tag.name %}" class=" tag">{{ tag.name }}</a>
        {% endfor %}
    </div>
    {% if post.audio_file %}
    <audio controls>
        <source src="{{ post.audio_file.url }}" type="audio/mp3">
        Your browser does not support the audio element.
    </audio>
    {% endif %}
    <div class="w-75 text lh-3 fs-5" >{{ post.text|safe }}</div>
    
    
</article>

{% if post.author.img %}
<img src="{{ post.author.img.url }}" class="img-thumbnail me-3" width="50px" height="50px"
    alt="{{ post.author.username }}'s Image">
{% endif %}
<h2 class="card-title " >
    <small  class="custom-font mb-3 fs-5 ">{{ post.author.username }}</small>
</h2>

<h3>Add Comment</h3>
<form method="post" action="">
    {% csrf_token %}
    <div id="commentForm" class="d-none">
        {{ comment_form.as_p }}
    </div>
    <button type="submit" class="btn btn-primary" onclick="showCommentBox()">Comment</button>
</form>


{% with comments.count as total_comments %}

{% endwith %}

{% if not post.comments.all %}
No comments yet

{% else %}
{% for comment in post.get_comments %}
{% include 'blog/comment.html' with comment=comment %}
{% endfor %}
{% endif %}
<script>
    const showCommentBox = () => {
        const form = document.querySelector('#commentForm');
        if (form.classList.contains('d-none')) {
    form.classList.remove('d-none');
    form.classList.add('d-block');
} else {
    form.classList.remove('d-block');
    form.classList.add('d-none');
}
    }
</script>
{% endblock %}

blog/templates/blog/tag_list.html
{% extends 'blog/base.html' %}

{% block content %}

<h1>Tags</h1>

<div class="catContainer">
    {% for tag in tags %}
    <a class="text-decoration-none text-black" href="{% url 'blog:Tag_post' tag_slug=tag.name %}">
        <p>
            {{tag.name}}
        </p>
    </a>
    {% endfor %}
</div>

{% endblock %}